---
title: "Gapminder Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(rnaturalearth)
library(dplyr)
library(sf)
library(shiny)

# Color palette
pal <- colorNumeric("YlOrRd", domain = NULL)

# Load African country boundaries
africa <- ne_countries(continent = "Africa", returnclass = "sf")
```

### Column {.sidebar}
--------------------------------------------------
```{r}
selectInput(inputId = "year", 
            label = "Select Year:", 
            choices = unique(gapminder::gapminder$year),
            selected = 2007)
```

### Column {data-width=650}
--------------------------------------------------

### African Countries 

```{r}
# Plot 
renderLeaflet({
  # Load gapminder data
  gapminder_africa <- gapminder::gapminder |> 
    filter(year == input$year, continent == "Africa")

  # Joining the dataframes by country name
  africa_data <- africa |>
    left_join(gapminder_africa, by = c("name" = "country"))
  
  # Plot with colors
  leaflet(africa_data) |>
  addTiles() |>
  addPolygons(fillColor = ~pal(lifeExp), 
              fillOpacity = 0.7
              ) |> 
  addLegend("bottomleft",
            pal = pal,
            values = ~lifeExp,
            title = "Life expectancy"
            )
})
```



